#ifndef EVENT_LOOP_H
# define EVENT_LOOP_H
#include <vector>

struct Conn {
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    std::vector<uint8_t> incoming;  // data to be parsed by the application
    std::vector<uint8_t> outgoing;  // responses generated by the application
};

void start_event_loop(int lst_sock);

#endif
